[package]
name = "premonition-core"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
std = ["dep:heapless"]

[dependencies]
num-traits.workspace = true
num-complex.workspace = true
serde = { workspace = true }
serde_json = { workspace = true }
heapless = { version = "0.8", optional = true }
